
services:
  mongodb:
    image: mongo:6-jammy
    expose:
      - 27017
    volumes:
      - mongodata:/data/db

  backend:
    depends_on:
      - mongodb
    build: ./express-api
    restart: unless-stopped
    expose:
      - 5000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/cosmoquiz

  client:
    depends_on:
      - backend
    build: ./client
    restart: unless-stopped
    expose:
      - 5001

  nginx:
    depends_on:
      - client
      - backend
    restart: always
    build: ./nginx
    ports:
      - '80:80'

volumes:
  mongodata: